name: 'f1_etl'
version: '1.0.0'
config-version: 2

profile: 'f1_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  f1_etl:
    materialized: 'table'
    