f1_etl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('RDS_HOST') }}"
      user: airflow
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: public